# AUTOGENERATED FILE; DO NOT MODIFY
# This file is autogenerated by bump-nixpkgs.hs.
#
# Updated: 2018-09-10
# Channels: nixos-18.03 nixpkgs-18.03-darwin

let fetchNixpkgs = import ./fetchNixpkgs.nix;
    nixpkgs = fetchNixpkgs {
      rev = "8b92a4e600458c01ab0a72f2492eb7120e18f9bc";
      sha256 = "13kz5p9xjbicd5dkyidl4pmxhxl6sq3293mr41n3k50v1y2j4vmg";
      unpackedSha256 = "1s28c24wydfiqkbz9x7bwhjnh2x4qr010p18si7xdnfdwrxn5mh1";
    };
in import nixpkgs {}

