# Package versions that should either override or augment the autogenerated
# list from Stackage in packages.bzl.
extra_packages = {
    "hedgehog-corpus": struct(
        version = "0.1.0",
        sha256 = "c3569cd8316770115871acf334587350e887b046e35abc0d52a90dd0e6d719f2",
    ),
    "lens-labels": struct(
        version = "0.2.0.1",
        sha256 = "929fea0fe771702780d309e4b2915327cde062a51219df5561bc18dac1c5c0da",
    ),
    "numeric-limits": struct(
        version = "0.1.0.0",
        sha256 = "8b956ce9ecf6465e19068885b77da623a3af23fcabf1253718edd2427c055153",
    ),
    "proto-lens-arbitrary": struct(
        version = "0.1.2.1",
        sha256 = "824e013d1f7c4d52434ea318aef63544491cf0e89f63dbcda4c4c07881b11c23",
    ),
    "except-exceptions": struct(
        version = "0.1",
        sha256 = "fa5b2430e4b3dcd496a174d63c61406af281c9dd82a30dd99ad6239cb322a90d",
    ),
    "formatting": struct(
        version = "6.3.4",
        sha256 = "9d038dc3d41081a95f4519102bfc4033a5ed077cf75e4a39a3e19860d7b796e5",
    ),
    "async-pool": struct(
        version = "0.9.0.2",
        sha256 = "e0159d13c974162ac3c06ade10ed319ae05d6b1b07e8e87ff4f8b40f9047e7f1",
    ),
    "cryptonite": struct(
        version = "0.24",
        sha256 = "17c3312343ef9bbfa87566d1f701d24870c2d34e015b104ff02faf1c9e1b5a86",
    ),
    "system-posix-redirect": struct(
        version = "1.1.0.1",
        sha256 = "53535011e64c1792052987bc1e8799222286c30c349dd36d3fc08c8612fa6ef2",
    ),
}
